kind: pipeline
name: first-line

steps:
- name: download
  image: plugins/git
  pull: true
- name: run-build
  image: node: 10.10.16
  commands:
    - npm install
    - npm run build

trigger:
  branch:
   - master
   event:
    - push