kind: pipeline
name: first-line

steps:
  - name: run-build
    image: node:alpine
    commands:
      - npm --registry https://registry.npm.taobao.org install
      - npm run build

  - name: copy-to-server
    image: appleboy/drone-scp
    settings:
      host: 182.61.43.63
      user:
        from_secret: scp_username
      password:
        from_secret: scp_password
      target:
        from_secret: scp_target
      source:
        from_secret: scp_source
      rm: true
  - name: restart -docker
    image: appleboy/drone-ssh
    settings:
    host: 182.61.43.63
      username:
        from_secret: scp_username
      password:
        from_secret: scp_password
      port: 22
      script:
        - docker restart react-server
