kind: pipeline
name: first-line

steps:
  - name: run-build
    image: node:alpine
    commands:
      - npm install
      - npm run build

  - name: copy-to-server
    image: appleboy/scp
    host: 182.61.43.63
    secrets:
      - source: USERNAME
        target: username
      - source: TARGET
        target: target
      - source: SOURCE
        target: source
    rm: true
