export const CREATE_QUESTION = "CREATE_QUESTION";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const SEARCH_QUESTION = "SEARCH_QUESTION";
export const SEARCH_QUESTION_BY_TITLE = "SEARCH_QUESTION_BY_TITLE";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const SEARCH_QUESTION_BY_TYPE = "SEARCH_QUESTION_BY_TYPE";
