// QUESTION TYPES
export const CREATE_QUESTION = "CREATE_QUESTION";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const SEARCH_QUESTION = "SEARCH_QUESTION";
export const SEARCH_QUESTION_BY_TITLE = "SEARCH_QUESTION_BY_TITLE";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const SEARCH_QUESTION_BY_TYPE = "SEARCH_QUESTION_BY_TYPE";

// AUTH TYPES
export const ASK_FOR_AUTH = "ASK_FOR_AUTH";
export const ASK_FOR_LOGIN = "ASK_FOR_LOGIN";
export const ASK_FOR_USER = "ASK_FOR_USER";
export const ASK_FOR_LOGOUT = "ASK_FOR_LOGOUT";

// MANAGE TYPES
export const MANAGE_LOAD_DEFAULT_QUESTION = "MANAGE_LOAD_DEFAULT_QUESTION";
export const MANAGE_REFRESH_QUESTION_LIST = "MANAGE_REFRESH_QUESTION_LIST";
export const MANAGE_PAGE_BACKFORWARD = "MANAGE_PAGE_BACKFORWARD";
export const MANAGE_PAGE_PREVIOUS = "MANAGE_PAGE_PREVIOUS";
export const MANAGE_UPDATE_QUESTION = "MANAGE_UPDATE_QUESTION";
