
// QUESTION TYPES
export const CREATE_QUESTION = "CREATE_QUESTION";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const SEARCH_QUESTION = "SEARCH_QUESTION";
export const SEARCH_QUESTION_BY_TITLE = "SEARCH_QUESTION_BY_TITLE";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const SEARCH_QUESTION_BY_TYPE = "SEARCH_QUESTION_BY_TYPE";

// AUTH TYPES
export const ASK_FOR_AUTH = "ASK_FOR_AUTH";
export const ASK_FOR_LOGIN = "ASK_FOR_LOGIN";